title: Tony McGee
production_url: http://www.tonymcgee.net

author:
  name: Tony McGee
  email: tmcgee.au@gmail.com (Tony McGee)

exclude: [_templates/]
permalink: /:year/:month/:day/:title 
port: 8890
